### ISSUE TITLE
Upgrade to wkhtmltopdf v0.12.5

### ISSUE THREAD

**Issue by waissbluth** [zeplin/zeplin-html-to-pdf#22]
If I am not mistaken, the binary for wkhtmltopdf included in `lib` corresponds to version 0.12.4 (is this documented somewhere?).

What would it take to upgrade to 0.12.5 (the [latest published version](https://github.com/wkhtmltopdf/wkhtmltopdf/releases))? The packaging strategy seems to have changed between these two versions, and it is not clear which binary (if any) would work with the Lambda environment. I would guess `wkhtmltox-0.12.5-1.centos7.x86_64.rpm` is the closest one, but I have not been able to get it to work.

[This post](https://majestic.cloud/how-to-install-wkhtmltopdf-on-amazon-linux/) provides some guidance, but it is unclear how to get it working inside the Lambda.

**Comment by dorukgunes** [comment]
Hey @waissbluth the wkhtmltopdf binary is 0.12.4 as you said, we will also add this information to the readme, thank you!

Let me show which steps I follow:
1 - Download `wkhtmltox-0.12.5-1.centos7.x86_64.rpm` and extract it with `rpm2cpio wkhtmltox-0.12.5-1.centos7.x86_64.rpm | cpio -idmv`
2 - Copy the `wkhtmltopdf` binary inside extracted folder `usr/local/bin/wkhtmltopdf` and replace with `zeplin-html-to-pdf/lib/wkhtmltopdf`
3 - Run `sam local invoke "HtmlToPdf" -e events/example-event.json` with >=nodejs6.10 runtime (you can edit this inside `template.yml`)

The result seems similar to 0.12.4 binary, I didn't test it with actual lambda but since AWS SAM creates a lamda-like execution environment it will probably work on it as well, let me know if you have any problem/question.
